# Generated by Django 3.2.8 on 2021-10-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportemployees',
            name='leave_date',
            field=models.DateField(max_length=255),
        ),
    ]
