# Generated by Django 3.2.8 on 2021-10-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0002_alter_leavereportemployees_leave_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportemployees',
            name='end_date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leavereportemployees',
            name='hours_calc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leavereportemployees',
            name='start_date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
