# Generated by Django 3.2.8 on 2021-10-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0004_auto_20211029_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportemployees',
            name='kronos_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leavereportemployees',
            name='hours_calc',
            field=models.IntegerField(default=0),
        ),
    ]
